### ISSUE TITLE
aar 集成路由报错

### ISSUE THREAD

**Issue by startfromandroid** [gfaraday/g_faraday#22]
我在aar 集成的时候路由报错，报错信息如下：
flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method reCreateLastPage on channel g_faraday)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
    <asynchronous suspension>
    #1      FaradayNativeBridgeState.recreateLastPage (package:flutter_module_test/src/faraday/route/native_bridge.dart:95)
    <asynchronous suspension>
本地开发环境： Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)

**Comment by KevinGong2013** [comment]
是不是在Native侧还没有setup Engine
