### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by phil-zZ** [gfaraday/g_faraday#5]
- pubspec.yaml
```yaml
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  g_faraday: ^0.5.1-nullsafety.19
  fluro: any
```

```
Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:fluro
```

求解这个怎么解决啊

**Comment by KevinGong2013** [comment]
`flutter run --no-sound-null-safety`

**Comment by phil-zZ** [comment]
@KevinGong2013 

结合原生App使用时，这个参数怎么加呢
```shell
set -e
set -u
source "${SRCROOT}/../app/.ios/Flutter/flutter_export_environment.sh"
"$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build
```

**Comment by KevinGong2013** [comment]
这种方式引用的时候直接编译应该就是可以的。
错误日志方便截图看一下吗？

**Comment by phil-zZ** [comment]
[Build KyiOS_2021-01-06T19-21-10.txt](https://github.com/gfaraday/g_faraday/files/5775474/Build.KyiOS_2021-01-06T19-21-10.txt)
这是错误日志，感谢

**Comment by phil-zZ** [comment]
我发现，需要在flutter端，
先运行一下`flutter build ios --no-sound-null-safety`, 
然后再运行原生App就可以了
不知道这其中是什么原因

**Comment by KevinGong2013** [comment]
你有新建module吗？
这里看到怎么在编译`lib/src/pages/features/basic/pages/flutter_to_native.dart`这个路径的东西。

**Comment by KevinGong2013** [comment]
> 我发现，需要在flutter端，
> 先运行一下`flutter build ios --no-sound-null-safety`,
> 然后再运行原生App就可以了
> 不知道这其中是什么原因

那你运行一下 `flutter build ios --no-sound-null-safety` 然后删除`.dart_tool` 再试试看

**Comment by phil-zZ** [comment]
> > 我发现，需要在flutter端，
> > 先运行一下`flutter build ios --no-sound-null-safety`,
> > 然后再运行原生App就可以了
> > 不知道这其中是什么原因
> 
> 那你运行一下 `flutter build ios --no-sound-null-safety` 然后删除`.dart_tool` 再试试看

报错
`.dart_tool/package_config.json does not exist.
Did you run this command from the same directory as your pubspec.yaml file?`

**Comment by phil-zZ** [comment]
> 你有新建module吗？
> 这里看到怎么在编译`lib/src/pages/features/basic/pages/flutter_to_native.dart`这个路径的东西。

我是自己新建了一个module，然后把g_farady下面的example拷进了我的module里面的

**Comment by KevinGong2013** [comment]
那估计还是`null-safety`的问题，你还是暂时先`flutter build` 一次吧。 😢

**Comment by phil-zZ** [comment]
如果只是这样的话就好了，关键问题是没法hotreload了
```shell
(base) ➜  app git:(feature/flutter+faraday) ✗ flutter attach --no-sound-null-safety --debug-uri http://127.0.0.1:51618/ar96Ufed6vo\=/                                     
lib/src/pages/features/basic/pages/flutter_to_native.dart:33:41: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        await Navigator.of(context)                     
                                        ^                               
lib/src/pages/features/basic/pages/flutter_to_native.dart:41:41: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        await Navigator.of(context)?.pushNamed<Object?>(
                                        ^                               
lib/src/pages/mine/app_about_page.dart:48:23: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
            Navigator.of(context)?.pop('Result From Flutter');          
                      ^                                                 
lib/src/pages/mine/app_about_page.dart:79:35: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        Navigator.of(context)?.pop('Result From Flutter'),
                                  ^                                     
lib/src/pages/features/basic/pages/flutter_to_flutter.dart:35:29: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  Navigator.of(context)?.push(                          
                            ^                                           
lib/src/pages/features/basic/pages/flutter_to_flutter.dart:50:44: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                onPressed: () => Navigator.of(context)?.nativePushNamed(
                                           ^                            
lib/src/pages/features/basic/pages/native_to_flutter.dart:29:31: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                    Navigator.of(context)?.pop('Result From Flutter'),  
                              ^                                         
lib/src/pages/features/basic/pages/transparent_page.dart:39:37: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          Navigator.of(context)?.pop(true);             
                                    ^                                   
lib/src/pages/features/basic/pages/transparent_page.dart:58:34: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
          onTap: () => Navigator.of(context)?.maybePop(),               
                                 ^                                      
lib/src/pages/home_page.dart:40:52: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        onPressed: () => Navigator.of(context)?.pop(false),
                                                   ^                    
lib/src/pages/home_page.dart:45:52: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        onPressed: () => Navigator.of(context)?.pop(true),
                                                   ^                    
lib/src/pages/features/basic/basic.dart:72:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('flutter2native',
                             ^                                          
lib/src/pages/features/basic/basic.dart:81:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('native2flutter',
                             ^                                          
lib/src/pages/features/basic/basic.dart:90:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('flutter2flutter',
                             ^                                          
lib/src/pages/features/basic/basic.dart:103:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('tabContainer'),
                             ^                                          
lib/src/pages/features/other/other.dart:32:40: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                onTap: () => Navigator.of(context)                      
                                       ^                                
lib/src/pages/features/other/other.dart:44:31: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                    Navigator.of(context)?.nativePushNamed('navigationBar');
                              ^                                         
lib/src/pages/features/other/other.dart:74:54: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          onPressed: () => Navigator.of(context)?.pop(false),
                                                     ^                  
lib/src/pages/features/other/other.dart:79:54: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          onPressed: () => Navigator.of(context)?.pop(true),
                                                     ^                  
lib/src/pages/features/other/other.dart:92:46: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  onPressed: () => Navigator.of(context)?.maybePop()),  
                                             ^                          
lib/src/pages/features/other/other.dart:95:46: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  onPressed: () => Navigator.of(context)?.pop()),       
                                             ^                          
lib/src/pages/features/splash/splash.dart:38:42: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
              onPressed: () => Navigator.of(context)?.push(CupertinoPageRoute(
                                         ^                              
Syncing files to device iPhone 12 Pro Max...                        9.0s

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:51659/XfrhkkEKcas=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

lib/src/pages/mine/app_about_page.dart:48:23: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
            Navigator.of(context)?.pop('Result From Flutter');          
                      ^                                                 
lib/src/pages/mine/app_about_page.dart:79:35: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        Navigator.of(context)?.pop('Result From Flutter'),
                                  ^                                     
lib/src/pages/home_page.dart:40:52: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        onPressed: () => Navigator.of(context)?.pop(false),
                                                   ^                    
lib/src/pages/home_page.dart:45:52: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        onPressed: () => Navigator.of(context)?.pop(true),
                                                   ^                    
lib/src/pages/features/splash/splash.dart:38:42: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
              onPressed: () => Navigator.of(context)?.push(CupertinoPageRoute(
                                         ^                              
lib/src/pages/features/other/other.dart:32:40: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                onTap: () => Navigator.of(context)                      
                                       ^                                
lib/src/pages/features/other/other.dart:44:31: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                    Navigator.of(context)?.nativePushNamed('navigationBar');
                              ^                                         
lib/src/pages/features/other/other.dart:74:54: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          onPressed: () => Navigator.of(context)?.pop(false),
                                                     ^                  
lib/src/pages/features/other/other.dart:79:54: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          onPressed: () => Navigator.of(context)?.pop(true),
                                                     ^                  
lib/src/pages/features/other/other.dart:92:46: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  onPressed: () => Navigator.of(context)?.maybePop()),  
                                             ^                          
lib/src/pages/features/other/other.dart:95:46: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  onPressed: () => Navigator.of(context)?.pop()),       
                                             ^                          
lib/src/pages/features/basic/basic.dart:72:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('flutter2native',
                             ^                                          
lib/src/pages/features/basic/basic.dart:81:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('native2flutter',
                             ^                                          
lib/src/pages/features/basic/basic.dart:90:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('flutter2flutter',
                             ^                                          
lib/src/pages/features/basic/basic.dart:103:30: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
      onTap: () => Navigator.of(context)?.nativePushNamed('tabContainer'),
                             ^                                          
lib/src/pages/features/basic/pages/flutter_to_native.dart:33:41: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        await Navigator.of(context)                     
                                        ^                               
lib/src/pages/features/basic/pages/flutter_to_native.dart:41:41: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                        await Navigator.of(context)?.pushNamed<Object?>(
                                        ^                               
lib/src/pages/features/basic/pages/flutter_to_flutter.dart:35:29: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                  Navigator.of(context)?.push(                          
                            ^                                           
lib/src/pages/features/basic/pages/flutter_to_flutter.dart:50:44: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                onPressed: () => Navigator.of(context)?.nativePushNamed(
                                           ^                            
lib/src/pages/features/basic/pages/transparent_page.dart:39:37: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                          Navigator.of(context)?.pop(true);             
                                    ^                                   
lib/src/pages/features/basic/pages/transparent_page.dart:58:34: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
          onTap: () => Navigator.of(context)?.maybePop(),               
                                 ^                                      
lib/src/pages/features/basic/pages/native_to_flutter.dart:29:31: Warning: Operand of null-aware operation '?.' has type 'NavigatorState' which excludes null.
 - 'NavigatorState' is from 'package:flutter/src/widgets/navigator.dart' ('../../../../../Tools/flutter/packages/flutter/lib/src/widgets/navigator.dart').
                    Navigator.of(context)?.pop('Result From Flutter'),  
                              ^                                         
Performing hot reload...                                               ⢿
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AppAboutPage(dirty, state:
_AppAboutPageState#32f44):
No constructor 'Text.' with matching arguments declared in class 'Text'.
Receiver: Text
Tried calling: new Text.()
Found: new Text.(String, {Key? key, TextStyle? style, StrutStyle? strutStyle, TextAlign? textAlign,
TextDirection? textDirection, Locale? locale, bool? softWrap, TextOverflow? overflow, double?
textScaleFactor, int? maxLines, String? semanticsLabel, TextWidthBasis? textWidthBasis,
TextHeightBehavior? textHeightBehavior}) => Text

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack:
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:212:5)
#1      _AppAboutPageState.build (package:app/src/pages/mine/app_about_page.dart)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4798:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4853:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4375:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2774:33)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:899:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#15     _invoke (dart:ui/hooks.dart:157:10)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#17     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
        
Reloaded 3 of 574 libraries in 469ms.
```

**Comment by phil-zZ** [comment]
只能HotRestart
![simulator_screenshot_ED24DA2D-7444-4941-A35F-1BC0FC96E190](https://user-images.githubusercontent.com/626401/103841240-0dcdac80-50ce-11eb-994f-ece3af982c4b.png)

**Comment by KevinGong2013** [comment]
```
name: g_faraday_example
description: Demonstrates how to use the g_faraday plugin.
version: 1.0.0+23

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
```

确认一下你的module, 配置的sdk是这个
`>=2.12.0-29.10.beta <3.0.0`

**Comment by phil-zZ** [comment]
- pubspec.yaml
```yaml
name: app
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  g_faraday: ^0.5.1-nullsafety.19
  package_info: ^0.4.3+2
  fluro: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - images/2.0x/
    - images/3.0x/
  
  module:
    androidX: true
    androidPackage: com.example.app
    iosBundleIdentifier: com.example.app

```

**Comment by KevinGong2013** [comment]
我前面说错了 sorry.
sdk 应该是更新为 `sdk: ">=2.9.0 <3.0.0"`

如果还是不行。尝试使用一下 `0.4.3`版本, 对应的为 `0.5.1-nullsafety.22`

> 我们自己这边attach暂时没有发现这个问题，也是很奇怪呢。

**Comment by phil-zZ** [comment]
你们attach不是用这个命令吗？
`flutter attach --app-id com.example.app`

**Comment by KevinGong2013** [comment]
我们是用这个命令，没问题


sdk 配置为 `sdk: ">=2.9.0 <3.0.0"` 默认是`--no-sound-null-safety`

**Comment by phil-zZ** [comment]
我现在的解决方案就是，
1. sdk 配置为:
`sdk: ">=2.9.0 <3.0.0"`
2. 删除项目里面的null-safety相关的代码
 例如: `object?.property` `object!`

现在项目运行正常，attach正常
